# Generated by Django 5.2.8 on 2026-01-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
