# Generated by Django 5.2.8 on 2026-01-19 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0002_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="description",
        ),
    ]
