# Generated by Django 5.2.8 on 2026-01-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0007_cartitem_delete_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="coffee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coffee.coffee",
            ),
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
