# Generated by Django 5.2.8 on 2026-01-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0008_remove_cartitem_product_cartitem_coffee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coffee",
            name="image",
            field=models.ImageField(upload_to="coffee_images/"),
        ),
    ]
