# Generated by Django 5.2.8 on 2026-03-03 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0009_alter_coffee_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coffee",
            name="quantity",
        ),
        migrations.AlterField(
            model_name="coffee",
            name="image",
            field=models.URLField(max_length=2083),
        ),
    ]
